USE [PRIVATE SCHOOL];
CREATE TABLE STUDENT(
STUDENT_ID INTEGER NOT NULL,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
DATEOFBIRTH DATE NOT NULL,
TUITIONFEES INTEGER NOT NULL,
CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_ID)
);