USE [PRIVATE SCHOOL];
CREATE TABLE ASSIGNMENT(
ASSIGNMENT_ID INTEGER NOT NULL,
TITLE VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR(50) NOT NULL,
SUBDATETIME DATE NOT NULL,
ORALMARK INTEGER,
TOTALMARK INTEGER,
CONSTRAINT PK_ASSIGNMENT PRIMARY KEY(ASSIGNMENT_ID)
);
