USE [PRIVATE SCHOOL];
CREATE TABLE TRAINERPERCOURSE(
TR_ID INTEGER NOT NULL,
C1_ID INTEGER NOT NULL,
CONSTRAINT PK_TPC PRIMARY KEY(TR_ID,C1_ID),
CONSTRAINT FK_TR_ID FOREIGN KEY(TR_ID) REFERENCES TRAINER(TRAINER_ID),
CONSTRAINT FK_C1_ID FOREIGN KEY(C1_ID) REFERENCES COURSE(COURSE_ID)
);