USE [PRIVATE SCHOOL];
CREATE TABLE ASSIGNMENTPERCOURSE(
AS_ID INTEGER NOT NULL,
C2_ID INTEGER NOT NULL,
CONSTRAINT PK_APC PRIMARY KEY(AS_ID,C2_ID),
CONSTRAINT FK_AS_ID FOREIGN KEY(AS_ID) REFERENCES ASSIGNMENT(ASSIGNMENT_ID),
CONSTRAINT FK_C2_ID FOREIGN KEY(C2_ID) REFERENCES COURSE(COURSE_ID)
);