USE [PRIVATE SCHOOL];
CREATE TABLE COURSE(
COURSE_ID INTEGER NOT NULL,
TITLE VARCHAR(50) NOT NULL,
STREAM VARCHAR(50) NOT NULL,
TYPE VARCHAR(50) NOT NULL,
STARTDATE DATE NOT NULL,
ENDDATE DATE NOT NULL,
CONSTRAINT PK_COURSE PRIMARY KEY(COURSE_ID)
);
