USE [PRIVATE SCHOOL];
INSERT INTO TRAINER(TRAINER_ID,FIRSTNAME,LASTNAME, SUBJECT)
VALUES
(101,'EKTORAS','GATZOS','C#'),
(102,'ARGYRIS','PAGIDAS','JAVA'),
(103,'CHRISTOS','PETROU','C#'),
(104,'MARIA','FOTOPOULOU','JAVA');
