SELECT s.FIRSTNAME,s.LASTNAME,c.TITLE COURSE_TITLE,c.STREAM,c.TYPE,a.TITLE ASSIGNMENT_TITLE,a.DESCRIPTION,a.SUBDATETIME
 FROM(ASSIGNMENT a INNER JOIN ASSIGNMENTPERCOURSE ON ASSIGNMENT_ID=AS_ID)
INNER JOIN COURSE c ON C2_ID=COURSE_ID INNER JOIN STUDENTPERCOURSE ON COURSE_ID=C_ID INNER JOIN STUDENT s
ON STUD_ID=STUDENT_ID ORDER BY STUDENT_ID;